data:
  source: winequality-red.csv
  type: csv
  target_column: quality
  sheet_name: null
preprocessing:
  missing_strategy: mean
  outlier_method: iqr
  outlier_threshold: 1.5
  normalize_types: true
  feature_engineering: true
hypothesis_search:
  pop_size: 100
  num_generations: 50
  cx_prob: 0.7
  mut_prob: 0.2
output:
  format: json
  file: null
